package space.dodoplanet.gildongmu.guide

import space.dodoplanet.gildongmu.kit.Fixtures
import kotlin.test.Test
import kotlin.test.assertEquals

/** spec §9 — M4가 쓰는 키 전량이 표에 있고 생성 카탈로그에도 실재한다(미매핑 키는 릴리스에서 키 문자열이 낭독된다). */
class GuideStringsTest {
    private val keys = listOf(
            "beacon.walkHeading",
            "beacon.stop",
            "beacon.first",
            "beacon.closer",
            "beacon.farther",
            "beacon.nearby",
            "beacon.weak",
            "beacon.denied",
            "beacon.reduced",
            "beacon.straightLineNote",
            "beacon.guideStartWalk",
            "android.beacon.guideStartWalkShortest",
            "guide.detailStart",
            "guide.bundle",
            "guide.handoff",
            "guide.finalApproachRouteEnd",
            "guide.finalApproachToDest",
            "guide.finalApproachToDestNoDir",
            "guide.finalApproachTick",
            "guide.finalApproachTickNoDir",
            "guide.finalApproachNear",
            "guide.finalApproachNearDir",
            "guide.arrived",
            "guide.arrivedPresumed",
            "guide.endedIdle",
            "guide.dirAhead",
            "guide.dirLeft",
            "guide.dirRight",
            "guide.dirBehind",
            "guide.dirAheadTo",
            "guide.dirLeftTo",
            "guide.dirRightTo",
            "guide.dirBehindTo",
            "guide.offRoute",
            "guide.backOnRoute",
            "guide.imminent.left",
            "guide.imminent.right",
            "guide.imminent.back",
            "guide.imminent.crosswalk",
            "guide.imminent.underpass",
            "guide.liveStraight",
            "guide.liveStraightNoName",
            "guide.liveTurnIn",
            "guide.liveAction.left",
            "guide.liveAction.right",
            "guide.liveAction.back",
            "guide.liveAction.crosswalk",
            "guide.liveAction.underpass",
            "guide.nextAction",
            "guide.nextStraight",
            "guide.nextStraightNoName",
            "guide.uncertain",
            "guide.uncertainRecovered",
            "guide.reacquiring",
            "guide.detailUnavailable",
            "guide.detailNoLocation",
            "guide.progressButton",
            "guide.progressOrdinal",
            "guide.progressCurrent",
            "guide.progressNext",
            "guide.remainingDistance",
            "guide.remainingTime",
            "guide.rerouteButton",
            "guide.rerouteBusy",
            "guide.rerouteFailed",
            "guide.rerouteDone",
            "android.guide.autoReroute",
            "guide.progressUncertain",
            "guide.progressOffRoute",
            "guide.progressFinalApproach",
            "guide.approx",
            "guide.rough",
            "guide.noGuidanceYet",
            "guide.alreadyActive",
            "guide.minimize",
            "guide.band.return",
            "guide.band.remaining",
            "guide.band.starting",
            "guide.band.arrived",
            "guide.band.ended",
            "guide.periodicStraight",
            "guide.periodicStraightNoName",
            "guide.nextDestination",
            "android.beacon.soundUnavailable",
            "android.beacon.stopped",
            "android.beacon.arrivedHeading",
            "android.beacon.arrivedPresumedHeading",
            "android.beacon.endedHeading",
            "android.beacon.healthSummary",
            "android.beacon.healthSummaryWithWeight",
            "android.beacon.food.cherryTomato",
            "android.beacon.food.cucumberHalf",
            "android.beacon.food.kimchi",
            "android.beacon.food.tangerine",
            "android.beacon.food.boiledEgg",
            "android.beacon.food.apple",
            "android.beacon.food.banana",
            "android.beacon.food.riceHalfBowl",
            "android.beacon.food.hotteok",
            "android.beacon.food.riceBowl",
            "android.beacon.food.ramyeon",
            "android.beacon.food.ramyeonMany",
            "android.guide.routeListCurrent",
            "android.guide.routeListRow",
            "android.guide.mediaVolumeZero",
            "android.guide.focusDenied",
            "android.guide.ttsUnavailable",
            "android.guide.serviceStartFailed",
            "android.guide.notificationChannel",
            "android.common.allowPrecise",
            "android.common.openSettings",
            "android.common.geoReducedDesc",
            "directions.viaArrived",
            "actions.close",
            "android.unit.spokenMeters",
    )

    @Test fun `M4가 쓰는 키 전부가 매핑돼 있다`() {
        assertEquals(emptyList(), keys.filter { guideStringId(it) == null })
    }

    @Test fun `매핑된 키는 생성 카탈로그에 실재한다`() {
        val xml = Fixtures.repoRoot.resolve("android/app/src/main/res/values/strings.xml").readText()
        assertEquals(emptyList(), keys.filter { !xml.contains("name=\"${it.replace('.', '_')}\"") })
    }

    @Test fun `모르는 키는 null이다`() {
        assertEquals(null, guideStringId("guide.doesNotExist"))
    }
}
